json.call(observation_image, 
          :id,
          :observation_id,
          :url,
          :url_thumbnail,
          :created_at,
          :updated_at,
          :license_code,
          :attribution
        )